resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rest
      namespace: nico-rest
    spec:
      template:
        spec:
          containers:
          - name: rest
            image: slaas/slaas-rest-app:latest